version: '3.7'
services:
  postgres_db:
    image: postgres:alpine3.17
    restart: always
    env_file:
      - ../../.env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '5432:5432'
    volumes:
      - ./volume/postgres-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
